services:
  api:
    container_name: seriesmanager-services
    image: seriesmanager-services
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    container_name: seriesmanager-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql